### ISSUE TITLE
Android device frames

### ISSUE THREAD

**Issue by davidbani** [carlashley/iphone_overlay#1]
Hi, thanks for creating this script, it has saved me alot of time. Any chance of creating overlays for Android devices? I know all us devs are busy, but I thought I should ask if you have time :-) No dramas if not possible, thanks again.

**Comment by carlashley** [comment]
Not particularly (this was pretty much an excuse to learn a bit about `ffmpeg` so it's more like a hobby tool) - there's an insane number of variations on Android devices, but I'd be happy to take pull requests on generic Android frames if anyone wanted to create a PR :)
